require:
  - rubocop/cop/internal_affairs
  - rubocop-rspec

AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_line
  Exclude:
    - 'lib/**/*.builder'
    - 'spec/**/*'

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - instance_methods
      - protected_methods
      - private_methods

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/xml/kit/self_signed_certificate.rb'

Metrics/BlockLength:
  Exclude:
    - '**/**/*.builder'
    - '**/*.rake'
    - '*.gemspec'
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  IgnoredPatterns: ['(\A|\s)#']
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/xml/kit/templates/*.builder'

Naming/FileName:
  Exclude:
    - 'lib/xml-kit.rb'

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: 'single_quotes'

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

RSpec/ExampleLength:
  Max: 80

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/xml/kit/templatable_spec.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/SubjectStub:
  Enabled: false

Style/DoubleNegation:
  Exclude:
    - 'lib/xml/kit/certificate.rb'
